# Site settings
title: College For All Temple University
email: templeydsa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: TempleYDSA
facebook_username: TUYDSA

# Build settings
markdown: kramdown
